### ISSUE TITLE
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'

### ISSUE THREAD

**Issue by ghuser** [dangvanthanh/vue-shopping-cart#4]
I get the following error when running: 

`deno cache server/deps.ts`

```
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { LogLevels, LevelName } from "./levels.ts";
                    ~~~~~~~~~
    at https://deno.land/std@0.62.0/log/mod.ts:13:21

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  RouterContext,
  ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/liamtan28/dactyl/master/deps.ts:6:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Middleware,
  ~~~~~~~~~~
    at https://raw.githubusercontent.com/liamtan28/dactyl/master/deps.ts:9:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { spy, Spy } from "https://deno.land/x/mock@v0.5.1/spy.ts";
              ~~~
    at https://raw.githubusercontent.com/liamtan28/dactyl/master/deps.ts:17:15

Found 4 errors.

```

```bash
$ deno --version
# deno 1.5.1
# v8 8.7.220.3
# typescript 4.0.3
```

**Note:** I have installed deno using with [asdf](https://github.com/asdf-vm/asdf)

**Comment by ghuser** [comment]
Seems to be related to this: https://deno.land/posts/v1.5#stricter-type-checks-in-stable

I tried adding `"isolatedModules": false` in `tsconfig.json` and run: `deno cache -c tsconfig.json server/deps.ts` and it worked.

Update: 

Now I tried downgrading and it works fine:

```bash
asdf local deno 1.4.6
deno cache server/deps.ts
```
